### ISSUE TITLE
InvalidRequest: The authorization mechanism you have provided is not supported. Please use AWS 4-HMAC-SHA256

### ISSUE THREAD

**Issue by prem911** [Upplication/gulp-elasticbeanstalk-deploy#6]
In my case, I m trying to use the ap-south-1.
Is there a problem with the api signature version?

http://stackoverflow.com/questions/26533245/the-authorization-mechanism-you-have-provided-is-not-supported-please-use-aws4
This suggests to use v4.

**Comment by Souler** [comment]
This should be fixed with the last release (v1.1.0), can you confirm it please?

**Comment by prem911** [comment]
Thanks it is fixed
