### ISSUE TITLE
Uploaded zip is deployed but Node application doesnot start

### ISSUE THREAD

**Issue by prem911** [Upplication/gulp-elasticbeanstalk-deploy#7]
The zip is uploaded to the bucket and not inside the application folder( as is done by eb deploy )
Downloaded and checked the contents. There are no missing files ( due to the gulp generation ).
However when this application is deployed, it results in module not found errors.
The app.js is the entry point, the nodejs dependent modules are loaded however the load fails for the application js modules.

**Comment by Souler** [comment]
I don't really understand what is the problem here. Can you try deploying the uploaded version of the plugin via the web ui and see if it deploys?

**Comment by prem911** [comment]
The zip is correct is S3. However in the EC2 instance, the permissions are all wrong for folders and files and hence the node server doesnot work. What can be done to fix the permissions during the unzip in EC2?

**Comment by Souler** [comment]
Mmm, I haven't heard of this issue before. What is your running OS on the machine you are deploying from? Can I get a copy of one of the zipped files so I can see what permissions are set (or at least an ls -al of the contents)? Could it be related to [this](https://github.com/sindresorhus/gulp-zip/issues/76)?

**Comment by prem911** [comment]
Its Amazon linux

Here is the dump
2017-01-11-11-01-52.zip  app  app.js  bin  config  node_modules
 package.json  public  routes  views
[ec2-user@ip-172-31-28-237 current]$ ls -al
total 48
drwxr-xr-x   9 nodejs nodejs 4096 Jan 11 05:39 .
drwxr-xr-x   3 root   root   4096 Jan 11 05:39 ..
drw-rw-rw-   3 nodejs nodejs 4096 Jan 11  2017 app
-rw-rw-rw-   1 nodejs nodejs 2751 Jan 11  2017 app.js
drw-rw-rw-   2 nodejs nodejs 4096 Jan 11  2017 bin
drw-rw-rw-   2 nodejs nodejs 4096 Jan 11  2017 config
drwxr-xr-x 180 nodejs nodejs 4096 Jan 11 05:39 node_modules
-rw-rw-rw-   1 nodejs nodejs 1477 Jan 11  2017 package.json
drw-rw-rw-   6 nodejs nodejs 4096 Jan 11  2017 public
drw-rw-rw-   2 nodejs nodejs 4096 Jan 11  2017 routes
drw-rw-rw-   4 nodejs nodejs 4096 Jan 11  2017 views
[ec2-user@ip-172-31-28-237 current]$ cd config/
-bash: cd: config/: Permission denied

**Comment by prem911** [comment]
Looks like there is a problem with gulp-zip. I created a task and created a zip using gulp-zip. File permissions change and hence the resulting deployment in nodejs also fails.
I verified this by manually creating a zip and uploading it to AWS beanstalk application and the deployment went fine.

**Comment by Souler** [comment]
Ok, having narrowed the problem the only solution I can think of is switching gulp-zip for some other ziping module that actually works under Windows/OSX (which I assume is the SO you are developing on). I'll try yo give ir a try tonight and post back here.

Also thanks for the feedback so far!

**Comment by prem911** [comment]
Thanks. Mine is windows 10.

**Comment by prem911** [comment]
Any update on this?

**Comment by greggmojica** [comment]
Same here. Any thoughts??

**Comment by Souler** [comment]
Not really. I've been digging around searching for zipping/archivers modules and all of them have an issue related with the current issue. Do you know of any module that works correctly between different OS installations (no need for it to be stream-oriented, i'll take care of that)?

**Comment by jarnaiz** [comment]
Hello,

I think this workaround maybe can solve the problem: https://github.com/sindresorhus/gulp-zip/issues/64#issuecomment-191659258
Related to: https://github.com/phonegap/build/issues/495#issuecomment-213127632 and https://github.com/sindresorhus/gulp-zip/issues/62

I dont test it, if its works, please tell us, 
Thanks :)

**Comment by wolfit** [comment]
Yes, this workaround works well (Tested on Windows 10).
You could consider update your README with info on this and close this issue.
.....], { base: './'**, nodir: true**})......

**Comment by Souler** [comment]
Done. Thank you for you feedback @wolfit
